export const BLURBS = {
    trash: "Odor-powered storage cylinder. Locals stuff it with their failed experiments.",
    gnome: "Frozen garden sentinel. Hat-first combat doctrine. Does not blink. Cannot blink.",
    mailbox: "Horizontal scream box. Humans feed it paper and wait for it to scream back.",
    frog: "Moisture-powered hop unit. Stores weather in its throat for later.",
    chicken: "Self-warming egg engine. Loud, feathery, and legally a factory.",
    cat: "Soft murder loaf. Sleeps 19 hours so the remaining 5 can be personal.",
    dog: "Loyalty-powered bark hose. Will trade dignity for a thrown stick.",
    sheep: "A cloud that forgot how to fly and took up chewing as a hobby.",
    wheelbarrow: "One-wheeled dirt chariot. Requires a human engine. Very embarrassing.",
    cow: "Grass-to-milk conversion tank. Spots are not windows. We checked.",
    deer: "Forest antenna with legs. The branches on its head pick up gossip.",
    human: "Upright snack that talks back. Collects smaller objects and calls it a personality.",
    motorcycle: "Two-wheel scream insect. Riders strap on and pretend they are the engine.",
    horse: "Long-face hay processor. Fast, judgmental, and mostly made of knee.",
    car: "Family-sized road beetle. Humans sit inside and argue about temperature.",
    tractor: "Dirt-chewing yellow god. Moves slower than thought. Still wins.",
    van: "Windowed cargo cave. May contain humans, boxes, or both, unsorted.",
    house: "Human nesting cube. They go in at night and become quieter, usually.",
    barn: "Red livestock warehouse. Smells like a successful civilization.",
    theatre: "Dark cave of pretend emotions. Humans pay to watch other humans lie.",
    mall: "Temple of bags. Pilgrims walk in circles until their feet surrender.",
    bigfoot: "Unlicensed forest intern. Very shy. Extremely unemployed.",

    hydrant: "Street mushroom of emergency water. Dogs consider it a messaging app.",
    bench: "Butt-parking plank. Humans sit here to rest from walking two blocks.",
    pedestrian: "Unlicensed outdoor human. No vehicle. Just vibes and crosswalks.",
    taxi: "Yellow kidnapping beetle, consensual edition. You point, it complains.",
    sedan: "Boring road beetle. Four doors of shame. Zero personality. Maximum commute.",
    bus: "People submarine on wheels. Packed with strangers who agreed not to make eye contact.",
    firetruck: "Red panic wagon. Arrives after something already became a problem.",
    bungalow: "One-floor nest. Ambition was discussed and then politely declined.",
    shop: "Box that trades shiny rocks for other boxes. Capitalism, but shorter.",
    bakery: "Warm cube of bread chemistry. Locals queue to eat yesterday's flour.",
    butcher: "Meat counter with a polite smile. The inventory used to walk.",
    cafe: "Caffeine temple. Humans pay extra to sit near other humans and ignore them.",
    supermarket: "Indoor field of boxes. Enter hungry. Leave with a bag of decisions.",
    townhouse: "Skinny house wearing another house as a hat. Neighbors hear everything.",
    apartment: "Stacked human drawers. Each floor contains a slightly different argument.",
    office: "Sad rectangle of sitting. Humans go here to look at smaller rectangles.",

    penguin: "Tuxedo ice missile. Formal wear is not optional. Formal wear is the body.",
    seal: "Wet loaf with a face. Applauds itself by slapping the floor.",
    polarbear: "White murder cloud. Looks like a pillow. Is not a pillow.",
    meerkat: "Dirt periscope. Stands up so the whole species can panic together.",
    flamingo: "Pink question mark. One-leg stance is a religious position.",
    zebra: "Horse that printed itself wrong and decided that was a brand.",
    lion: "Mane-powered roar engine. Sleeps like a king. Hunts like a group project.",
    giraffe: "A neck that forgot to stop. The spots are just leftover confidence.",
    elephant: "Grey building that walks, poorly. Nose is a spare arm. We are jealous.",
    monkey: "Hand-footed chaos unit. Steals anything not bolted to the planet.",
    panda: "Bamboo-powered pillow. Endangered because it will not eat literally anything else.",
    gorilla: "Muscle furniture. Chest-thump is a status update.",
    hippo: "River boulder with opinions. Smiles with the entire murder toolkit.",
    visitor: "Human who paid to stand next to lunch. Takes pictures of the real specimens.",
    tram: "Slow park worm. Humans sit in it so they can see animals without walking.",
    giftshop: "Plush prison. Every object inside is a worse version of a living thing.",
    gate: "A fence that learned a job. Opens. Closes. Judges you silently.",
};
